// apps/angular-demo/src/app/app.component.ts
import { ChangeDetectionStrategy, Component, ViewChild, computed, signal } from "@angular/core";
import { VisualFlowAngularComponent } from "@sentimental37/visual-flow-angular";
import { angularDemos, type AngularDemoKey } from "./diagrams";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [VisualFlowAngularComponent],
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.css",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  @ViewChild(VisualFlowAngularComponent) private diagram?: VisualFlowAngularComponent;

  protected readonly demos = angularDemos;
  protected readonly activeKey = signal<AngularDemoKey>("platform");
  protected readonly ready = signal(false);
  protected readonly error = signal<string | null>(null);
  protected readonly active = computed(() =>
    this.demos.find((demo) => demo.key === this.activeKey()) ?? this.demos[0],
  );
  protected readonly diagramOptions = { panZoom: true } as const;

  protected select(key: AngularDemoKey): void {
    this.error.set(null);
    this.activeKey.set(key);
  }

  protected markReady(): void {
    this.ready.set(true);
  }

  protected reportError(error: unknown): void {
    this.error.set(error instanceof Error ? error.message : "Unable to render this diagram.");
  }

  protected exportSvg(): void {
    const svg = this.diagram?.exportSvg();
    if (!svg) return;
    const url = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml;charset=utf-8" }));
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${this.active().spec.id}.svg`;
    anchor.click();
    URL.revokeObjectURL(url);
  }
}

<main>
  <header class="topbar">
    <a class="brand" href="https://github.com/sentimental37/visual-flow-kit" aria-label="Visual Flow Kit on GitHub">
      <span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span>
      <span>Visual Flow <b>Kit</b></span>
    </a>
    <div class="framework-pill"><span class="angular-mark">A</span> Native Angular adapter</div>
    <a class="repo-link" href="https://github.com/sentimental37/visual-flow-kit">View repository <span>↗</span></a>
  </header>

  <section class="hero">
    <div class="hero-copy">
      <p class="eyebrow">Angular integration showcase</p>
      <h1>Architecture that feels <em>alive.</em></h1>
      <p class="lede">Portable diagram JSON, rendered through a native standalone Angular component—with strict templates, zoneless change detection, pan, zoom, motion, and export.</p>
    </div>
    <div class="facts" aria-label="Integration facts">
      <div><strong>17–22</strong><span>Angular support</span></div>
      <div><strong>0</strong><span>framework lock-in</span></div>
      <div><strong>SVG</strong><span>crisp at any size</span></div>
    </div>
  </section>

  <section class="showcase" aria-labelledby="diagram-title">
    <aside class="catalog">
      <p class="section-label">Choose a story</p>
      @for (demo of demos; track demo.key; let index = $index) {
        <button type="button" [class.active]="activeKey() === demo.key" (click)="select(demo.key)">
          <span class="item-index">0{{ index + 1 }}</span>
          <span class="item-copy"><b>{{ demo.label }}</b><small>{{ demo.kicker }}</small></span>
          <span class="arrow">→</span>
        </button>
      }
      <div class="integration-note">
        <span class="pulse"></span>
        <div><b>Angular lifecycle owned</b><small>Safe updates, cleanup, and SSR guards are built into the adapter.</small></div>
      </div>
    </aside>

    <article class="canvas-card">
      <header class="canvas-header">
        <div>
          <p>{{ active().kicker }}</p>
          <h2 id="diagram-title">{{ active().spec.title }}</h2>
          <span>{{ active().summary }}</span>
        </div>
        <button type="button" class="export-button" (click)="exportSvg()" [disabled]="!ready()">Export SVG</button>
      </header>

      <div class="diagram-shell">
        <div class="grid-glow"></div>
        <visual-flow-diagram
          [spec]="active().spec"
          [options]="diagramOptions"
          (visualFlowReady)="markReady()"
          (visualFlowError)="reportError($event)"
        />
      </div>

      <footer class="canvas-footer">
        <span class="status" [class.error]="error()"><i></i>{{ error() ?? (ready() ? "Angular component ready" : "Rendering diagram…") }}</span>
        <code>{{ active().spec.id }}.visual-flow.json</code>
        <span>{{ active().metric }}</span>
      </footer>
    </article>
  </section>

  <section class="code-strip">
    <div><span class="step">01</span><p><b>Import</b><code>VisualFlowAngularComponent</code></p></div>
    <span class="connector">→</span>
    <div><span class="step">02</span><p><b>Bind portable JSON</b><code>[spec]="architecture"</code></p></div>
    <span class="connector">→</span>
    <div><span class="step">03</span><p><b>Ship everywhere</b><code>Angular · React · Next.js · Web</code></p></div>
  </section>
</main>

// apps/gallery/src/App.tsx
import { useState } from "react";
import { VisualFlow } from "@sentimental37/visual-flow-react";
import { demos, type DemoKey } from "./diagrams.js";

const demoKeys = Object.keys(demos) as DemoKey[];

function Mark() {
  return <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M5 8h8v8H5zM19 16h8v8h-8z" /><path d="M13 12h3a5 5 0 0 1 5 5" /><path d="m18 5 4 3-4 3" /></svg>;
}

export function App() {
  const [activeKey, setActiveKey] = useState<DemoKey>("commerce");
  const active = demos[activeKey];

  return (
    <main className="gallery-shell">
      <header className="nav">
        <a className="wordmark" href="#top"><span><Mark /></span><strong>Visual Flow <i>Kit</i></strong></a>
        <nav aria-label="Primary navigation"><a href="#gallery">Gallery</a><a href="#frameworks">Frameworks</a><a href="https://github.com/sentimental37/visual-flow-kit">GitHub</a></nav>
        <a className="builder-link" href="http://127.0.0.1:4317">Open builder <span>↗</span></a>
      </header>

      <section className="hero" id="top">
        <div>
          <span className="kicker"><i /> Source-controlled visual systems</span>
          <h1>Architecture you can <em>feel.</em></h1>
          <p>Build sleek, interactive diagrams from portable JSON—then render them anywhere on the web.</p>
        </div>
        <div className="hero-meta">
          <span><strong>SVG</strong><small>crisp at every scale</small></span>
          <span><strong>JSON</strong><small>diffable source</small></span>
          <span><strong>0 lock-in</strong><small>framework neutral</small></span>
        </div>
      </section>

      <section className="showcase" id="gallery">
        <aside className="demo-menu">
          <div className="demo-menu__heading"><small>Live collection</small><strong>Choose a system</strong></div>
          {demoKeys.map((key, index) => {
            const demo = demos[key];
            return <button className={activeKey === key ? "is-active" : ""} key={key} type="button" onClick={() => setActiveKey(key)}>
              <span>0{index + 1}</span><div><small>{demo.eyebrow}</small><strong>{demo.spec.title}</strong><p>{demo.summary}</p></div><i>→</i>
            </button>;
          })}
          <div className="portable-note"><span>⌘</span><div><strong>One portable model</strong><p>The same source powers static SVG, React canvases, Angular components, and agent-generated docs.</p></div></div>
        </aside>

        <article className={`diagram-card diagram-card--${active.spec.theme}`}>
          <header><div><span>{active.eyebrow}</span><h2>{active.spec.title}</h2></div><div className="live-pill"><i /> live diagram</div></header>
          <div className="diagram-stage"><VisualFlow key={activeKey} spec={active.spec} showControls showMiniMap={false} style={{ width: "100%", height: "100%" }} /></div>
          <footer><span>{active.stat}</span><code>{active.spec.id}.visual-flow.json</code><span className="hint">pan · zoom · explore</span></footer>
        </article>
      </section>

      <section className="framework-strip" id="frameworks">
        <span>Render everywhere</span>
        <div>{["Vanilla JS", "React", "Next.js", "Angular", "Vue", "Svelte", "Astro", "Web Components"].map((name) => <i key={name}>{name}</i>)}</div>
      </section>
    </main>
  );
}
